// <auto-generated />
namespace FSEFCore.Migrations

open System
open FSEFCore
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<Context>)>]
[<Migration("20211018202154_Foo")>]
type Foo() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Foos"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Guid>(
                        nullable = false
                        ,``type`` = "uniqueidentifier"
                    )
                Name =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                Bar =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Foos", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Foos"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.9")
            |> ignore

        modelBuilder.Entity("FSEFCore.Foo", (fun b ->

            b.Property<Guid>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier") |> ignore
            b.Property<int>("Bar")
                .IsRequired(true)
                .HasColumnType("int") |> ignore
            b.Property<string>("Name")
                .IsRequired(false)
                .HasColumnType("nvarchar(max)") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Foos") |> ignore

        )) |> ignore

